chef-partners/azure-chef-extension

- ChefExtensionHandler/bin/chef-update.sh
This happened because `auto_update_client` variable executes ruby code which needs ruby path to be exported.
> Extension update failing

- lib/chef/azure/commands/enable.rb
- spec/unit/azure_enable_spec.rb
Implemented changes to fix validation key related parsing issues for win2k8r2 platform
> Fixed validation key parsing related issues on win2k8r2 platform

- lib/chef/azure/bootstrap/chef-full.erb
- lib/chef/azure/bootstrap/windows-chef-client-msi.erb
- lib/chef/azure/commands/enable.rb
- lib/chef/azure/core/bootstrap_context.rb
- lib/chef/azure/core/windows_bootstrap_context.rb
I've added changes to fix minor typo and restructured code according to latest windows bootstrap context and chef 12 bootstrap template .
> Fixed issues related to pass JSON attributes

- lib/chef/azure/core/bootstrap_context.rb
The Chef log doesn't show individual resources converging. Set log level to info
> Added log_level attribute and set it to info for detailed log

- lib/chef/azure/commands/enable.rb
- lib/chef/azure/core/bootstrap_context.rb
- lib/chef/azure/core/windows_bootstrap_context.rb
- spec/unit/azure_enable_spec.rb
Added changes to append extension generated config to end of the client_rb to get higher precedence.
> Implemented changes to append extension generated config to client_rb

- lib/chef/azure/commands/enable.rb
- lib/chef/azure/service.rb
- spec/functional/disable_cmd_spec.rb
- spec/unit/azure_enable_spec.rb
- spec/unit/service_spec.rb
w.r.t. https://github.com/chef-partners/azure-chef-extension/issues/9
> Azure extension failing with timeout error

- lib/chef/azure/bootstrap/chef-full.erb
- lib/chef/azure/bootstrap/windows-chef-client-msi.erb
Added changes  fixed empty client_key issue related to bootstrap template.
> Fixed empty client_key/validation_key issue

- scripts/deletepkg.psm1
- scripts/publishpkg.psm1
- scripts/shared.psm1
- scripts/uploadpkg.psm1
This fixes following issues:
1. Import-AzureSubscription gives error that the publishsettings file is being used by another process
2. Get-AzureSubscription doesn't return management certificate
3. Poll-AzureOperationStatus fails
> Updated scripts according to latest PS command behaviour

- ChefExtensionHandler/bin/chef-install.sh
- ChefExtensionHandler/install.sh
For https://github.com/chef-partners/azure-chef-extension/issues/17
> Adding support for centos

- README.md
- examples/README.md
- examples/azure-powershell-examples.md
- examples/azure-xplat-cli-examples.md
- examples/knife-azure-plugin-examples.md
Added examples for azure chef extension for Windows , Centos and Ubuntu platform. 
Please refer `azure-chef-extension/examples/` folder
> Implemented changes for Chef Extension usage examples 

- lib/chef/azure/bootstrap/chef-full.erb
- lib/chef/azure/bootstrap/windows-chef-client-msi.erb
- lib/chef/azure/commands/enable.rb
- lib/chef/azure/core/bootstrap_context.rb
- lib/chef/azure/core/windows_bootstrap_context.rb
- spec/unit/azure_enable_spec.rb
> Added SSL certificate bootstrap support in chef extension for cloud-api protocol.

- ChefExtensionHandler/bin/chef-update.psm1
- ChefExtensionHandler/bin/chef-update.sh
`autoUpdateClient=false` doesn't work properly currently. Hence this is a temporary fix.
> Setting autoUpdateClient=true

- ChefExtensionHandler/bin/chef-install.psm1
- ChefExtensionHandler/bin/chef-install.sh
- ChefExtensionHandler/bin/chef-update.psm1
- ChefExtensionHandler/bin/chef-update.sh
- ChefExtensionHandler/uninstall.cmd
- ChefExtensionHandler/uninstall.sh
Phase-1 of https://github.com/chef-partners/azure-chef-extension/issues/98
> Not removing chef-client on extension uninstall

- ChefExtensionHandler/bin/chef-update.psm1
- ChefExtensionHandler/bin/chef-update.sh
> Added code to delete node-registered file during update process as it was not allowing chef-client run during enable process after update.

- CHANGELOG.md
- README.md
- RELEASE_NOTES.md
- release_tracking.txt
W.R.T Card #212
updated release note for extension 1210.12.101.1000 for Windows and 1210.12.101.1000 for Ubuntu
> updated release note for extension 1210.12.101.1000 for Windows and 1210.12.101.1000 for Ubuntu

- ChefExtensionHandler/bin/chef-install.sh
- ChefExtensionHandler/bin/chef-uninstall.sh
> Added AzureChefExtension support for RHEL platform.

- ChefExtensionHandler/bin/chef-install.sh
- ChefExtensionHandler/bin/chef-uninstall.sh
- ChefExtensionHandler/bin/chef-update.sh
- ChefExtensionHandler/bin/shared.sh
Same methods were present in multiple files, so created a shared.sh file and moved all the duplicate methods there and rest of the files having those duplicate methods will import the shared.sh file
> Created a file for having command methods of Linuxchef extension

- lib/chef/azure/commands/enable.rb
- spec/functional/enable_cmd_spec.rb
- spec/unit/azure_enable_spec.rb
> Added support to read ohai_hints in extension.

- ChefExtensionHandler/bin/chef-install.sh
- ChefExtensionHandler/bin/chef-uninstall.sh
- ChefExtensionHandler/bin/chef-update.sh
- ChefExtensionHandler/bin/shared.sh
- ChefExtensionHandler/disable.sh
- ChefExtensionHandler/enable.sh
- README.md
> Added support to read environment variables from handler settings file.

- ChefExtensionHandler/bin/chef-install.psm1
> Added retry logic for chef-client download issue on Windows platform.

- ChefExtensionHandler/bin/chef-install.psm1
- ChefExtensionHandler/bin/chef-install.sh
> Add check for chef-client installation and to skip installation if exists

- ChefExtensionHandler/bin/chef-uninstall.psm1
- ChefExtensionHandler/bin/chef-update.psm1
- ChefExtensionHandler/bin/shared.ps1
- lib/chef/azure/service.rb
Removed `autoUpdateClient`, `uninstallChefClient` and `deleteChefConfig` flags
> Removed unwanted flags for windows

- ChefExtensionHandler/bin/chef-install.sh
- ChefExtensionHandler/bin/chef-uninstall.sh
- ChefExtensionHandler/bin/chef-update.sh
- ChefExtensionHandler/enable.sh
- ChefExtensionHandler/uninstall.sh
Code changes for removing autoUpdateClient, uninstallChefClient and deleteChefConfig flags on Linux Platforms
In-Progress
> Removed unrequired flags on Linux Platforms

- README.md
Some updates to the README that I discovered while implementing this extension in our environment.  Please let me know if you have any questions or concerns.  Thanks!
> Updates/Clarifications to README.md

- lib/chef/azure/commands/enable.rb
- spec/functional/secret_key_spec.rb
This PR fixes bug where empty encrypted_data_bag_secret file was getting created when no secret was being passed by the user.
> Fixed bug to not generate empty encrypted_data_bag_secret file.

- README.md
Update invalid references link in readme
> Update invalid references link in readme

- ChefExtensionHandler/bin/chef-install.psm1
- ChefExtensionHandler/bin/shared.ps1
- README.md
- lib/chef/azure/helpers/parse_json.rb
- spec/functional/chefserver_ssl_spec.rb
- spec/functional/validation_key_spec.rb
- spec/unit/parse_json_spec.rb
Added support for environment_variables in windows extension.
> Added support for environment_variables in windows extension.

- lib/chef/azure/helpers/parse_json.rb
- spec/functional/chefserver_ssl_spec.rb
- spec/functional/validation_key_spec.rb
- spec/unit/parse_json_spec.rb
Fixed extension bad format issue.
> Fixed extension bad format issue.

- ChefExtensionHandler/bin/chef-update.psm1
Signed-off-by: dheerajd-msys <dheeraj.dubey@msystechnologies.com>
> Fixed the issue of multiple directory backup

- ChefExtensionHandler/bin/chef-update.psm1
Reverts chef-partners/azure-chef-extension#201
> Revert "Fixed the issue of multiple directory backup"

- ChefExtensionHandler/bin/chef-update.psm1
w.r.t. https://github.com/chef-partners/azure-chef-extension/issues/198
> Fixed nested backup issue

- lib/chef/azure/bootstrap/chef-full.erb
- lib/chef/azure/bootstrap/windows-chef-client-msi.erb
- lib/chef/azure/commands/enable.rb
- lib/chef/azure/core/bootstrap_context.rb
- lib/chef/azure/core/windows_bootstrap_context.rb
- spec/functional/chefserver_ssl_spec.rb
w.r.t. open issue https://github.com/chef-partners/azure-chef-extension/issues/194
> Done changes for spliting multiple certificates

- README.md
Update Readme that the extension is verified against images from Microsoft and that other images may not be fully compatible with VM Agent extensions
> Update readme with microsoft image

- lib/chef/azure/commands/enable.rb
- lib/chef/azure/core/bootstrap_context.rb
- lib/chef/azure/core/windows_bootstrap_context.rb
- spec/unit/azure_enable_spec.rb
**Issue Resolved**
https://github.com/chef-partners/azure-chef-extension/issues/211
Cherry-picks https://github.com/chef-partners/azure-chef-extension/pull/212
> [MSYS-573] Runlist conflicts with policy_name and policy_group settings in first-boot.json

- ChefExtensionHandler/bin/chef-install.sh
- ChefExtensionHandler/bin/shared.sh
issue: https://github.com/chef-partners/azure-chef-extension/issues/233
Signed-off-by: piyushawasthi <piyush.awasthi@msystechnologies.com>
> [MSYS-695] Added support for oracle linux.

- ChefExtensionHandler/bin/chef-install.psm1
- ChefExtensionHandler/bin/chef-install.sh
Add bootstrap_channel option to azure chef extension.
`bootstrap_channel` can be set as `current`, `stable`, `unstable` 
> [MSYS-796] Add bootstrap_channel option to extension

- spec/unit/exception_handler_spec.rb
Signed-off-by: Vasu1105 <vasundhara.jagdale@msystechnologies.com>
> Fixes failing specs in recent merge which has wrong check of error code.

- Gemfile
- lib/chef/azure/helpers/parse_json.rb
- lib/chef/azure/service.rb
- spec/unit/azure_enable_spec.rb
- spec/unit/service_spec.rb
Also fixing some unreachable code and specs in this PR since came across it while testing.
Fixes #262
Signed-off-by: Vasu1105 <vasudhara.jagdale@msystechnologies.com>
> Fix for security vulnerability.

- ChefExtensionHandler/bin/chef-install.psm1
- ChefExtensionHandler/bin/chef-install.sh
Backporting changes to `1210.12.110.1001`
Signed-off-by: Nimesh-Msys <nimesh.patni@msystechnologies.com>
> Pin to Chef 14 until Chef 15 is tested and verified on Azure later this year

- ChefExtensionHandler/bin/shared.sh
> Add compatible python path for Rhel8

- lib/chef/azure/commands/enable.rb
**##Issue Fixed**
closes https://github.com/chef-partners/azure-chef-extension/issues/285
> [MSYS-1177] Fix empty runlist issue while passing policy_file 

- README.md
> Added usage of policy_name and policy_group

- ChefExtensionHandler/bin/chef-install.psm1
- ChefExtensionHandler/bin/chef-install.sh
- ChefExtensionHandler/bin/shared.sh
- ChefExtensionHandler/enable.cmd
- README.md
Support azure chef extension to chef-15
https://github.com/chef-partners/azure-chef-extension/issues/291
> Support azure chef extension to chef-15

- ChefExtensionHandler/bin/chef-install.psm1
- ChefExtensionHandler/bin/chef-install.sh
Added feature for chef_package_url for linux and windows system
https://github.com/chef-partners/azure-chef-extension/issues/297
> Added feature for chef_package_url for linux and windows system

- README.md
Signed-off-by: Vasu1105 <vasundhara.jagdale@chef.io>
> Updated README for OS support

- ChefExtensionHandler/bin/chef-install.sh
- ChefExtensionHandler/bin/chef-uninstall.sh
- ChefExtensionHandler/bin/shared.sh
Updated chef-install.sh with required improvements for using variable in place of $1 and $? 
issue resolve #321 
> Improvement in code of chef-install.sh

- .travis.yml
- lib/chef/azure/service.rb
- lib/chef/azure/task.rb
- spec/unit/service_spec.rb
- spec/unit/task_spec.rb
#273 
Addressing the issue of task getting failed when using Set-AzVMExtension to change the "daemon" setting from "service" to "task".
> Fix for inconsistent behavior with System Path and error while running dameon as service 

- ChefExtensionHandler/bin/shared.sh
Addressed the issue #334  of deployment failed in Ubuntu 20.04
Fixes #334
> Fix for failing deployment of Azure Chef extension in Ubuntu 20.04 

- MAINTAINERS.md
Signed-off-by: Vasu1105 <vasundhara.jagdale@chef.io>
> Updated maintainers docs

- azure-chef-extension.gemspec
Signed-off-by: NAshwini <anehate@chef.io>
> Pinned to chef-16 gem to fix rspec

- ChefExtensionHandler/bin/chef-install.psm1
- ChefExtensionHandler/bin/chef-install.sh
- azure-chef-extension.gemspec
> Pin to chef 16 until chef 17 is tested and verified in Azure

- ChefExtensionHandler/bin/chef-install.psm1
- ChefExtensionHandler/bin/chef-install.sh
> Unpinning Chef-Infra-Client-16 from azure-chef-extension

- azure-chef-extension.gemspec
> Unpinning chef-16 gem from gemspec file

- ChefExtensionHandler/bin/shared.sh
> Fixing indentation

- README.md
Documented how `chef_server_crt` is needed to be used with azure-chef-extension.
Fixes #277
> Documented the use of chef_server_crt option in azure-chef-extension

- Makefile
- Rakefile
- publish-template-default.json
> Changes for Rakefile for new process of publishing

- Makefile
> Update in makefile for automating the process

- Gemfile
Upgrading rack version from 2.0.6 to 2.1.4 to resolve directory traversal vulnerability [CVE-2020-8161](https://nvd.nist.gov/vuln/detail/CVE-2020-8161)
[INSUS-233 ](https://chefio.atlassian.net/browse/INFSUS-233)A directory traversal vulnerability exists in rack <2.2.0 that allows an attacker perform directory traversal vulnerability in the Rack::Directory app that is bundled with Rack which could result in information disclosure.
> INSUS-233 Upgrade rack version to 2.14 for azure-chef-extension

- .expeditor/config.yml
- .expeditor/publish.pipeline.yml
- Makefile
- scripts/internal-publish.sh
Signed-off-by: Shravani Roy <Shravani.Roy@progress.com>
Automate the internal release process for Azure-chef-extension
> INFSUS-235 Feasibility study for automating azure chef extension release pipeline
