lib/chef/azure/chefhandlers/exception_handler.rb

When the azure chef extension is used to create a node, if the initial run fails, the runlist is empty after that and the system never retries the runlist

Save runlist if first chef-client run fails

---

lib/chef/azure/commands/enable.rb

We are using bootstrap context and template to form chef config files. Updated escape logic accordingly.

Fixed runlist escape related changes

---

lib/chef/azure/commands/enable.rb
spec/unit/azure_enable_spec.rb

Providing multiple items in the runlist is failing for azure chef extension. Fixing this issue in this PR and also writing unit testcases for verifying runlist contents.

Fix for providing multiple runlist item

---

lib/chef/azure/bootstrap/chef-full.erb
lib/chef/azure/bootstrap/windows-chef-client-msi.erb
lib/chef/azure/commands/enable.rb

chef-service-manager/cronjob will take care of that.

Removed chef-client run with run_list part

---

ChefExtensionHandler/bin/chef-enable.rb
ChefExtensionHandler/bin/chef-install.psm1
ChefExtensionHandler/bin/chef-install.sh
ChefExtensionHandler/bin/chef-uninstall.psm1
ChefExtensionHandler/bin/chef-uninstall.sh
ChefExtensionHandler/bin/chef-update.psm1
ChefExtensionHandler/bin/chef-update.sh
ChefExtensionHandler/bin/shared.ps1
lib/chef/azure/chefhandlers/report_handler.rb
lib/chef/azure/commands/enable.rb
lib/chef/azure/core/bootstrap_context.rb
lib/chef/azure/core/windows_bootstrap_context.rb
lib/chef/azure/service.rb

Implemented changes to use old version extensions settings file during update process.
Example- 
Current extension is 1204.12.1.1
User requested update for extension 1205.12.2.1
In above case WaAgent will -
1. run disable on old extension 1204.12.1.1
2. run update command on 1205.12.2.1 and this should use previous version (i.e 1204.12.1.1) 0.settings file to get 'autoUpadteChef' and 'deleteChefConfig' options value
.
Currently update process trying to read 0.settings from newly downloaded extension, and this fails as this settings file not available during update, because WaAgent takes some time to create it.

Fixed update extension process related issues

---

lib/chef/azure/chefhandlers/exception_handler.rb
lib/chef/azure/chefhandlers/report_handler.rb
lib/chef/azure/chefhandlers/start_handler.rb
lib/chef/azure/helpers/shared.rb

While trying to update the extension from an older version(eg. 1205.12.2.1) to the latest version(eg. 1207.12.3.0) with `deleteChefConfig` option false in 0.settings file, C:\chef\client.rb( \etc\chef\client.rb in case of linux) file will have following contents at the end:
```
start_handlers << AzureExtension::StartHandler.new("C:/Packages/Plugins/Chef.Bootstrap.WindowsAzure.ChefClient/1205.12.2.1")
report_handlers << AzureExtension::ReportHandler.new("C:/Packages/Plugins/Chef.Bootstrap.WindowsAzure.ChefClient/1205.12.2.1")
exception_handlers << AzureExtension::ExceptionHandler.new("C:/Packages/Plugins/Chef.Bootstrap.WindowsAzure.ChefClient/1205.12.2.1")
```
But 1205.12.2.1 has got uninstalled during update. So, it will fail as `AzureExtension::ExceptionHandler.new("C:/Packages/Plugins/Ch …

Azure extension handler issue

---

lib/chef/azure/chefhandlers/exception_handler.rb
spec/unit/exception_handler_spec.rb

Fixed bug related to preserve runlist on first chef client run failure .

Fixed issue related to preserve runlist if first chef client run fails

---

lib/chef/azure/bootstrap/chef-full.erb
lib/chef/azure/bootstrap/windows-chef-client-msi.erb
lib/chef/azure/commands/enable.rb
lib/chef/azure/core/bootstrap_context.rb
lib/chef/azure/core/windows_bootstrap_context.rb
spec/unit/azure_enable_spec.rb

This changes right now only will work with knife-azure cloud-api bootstrap protocol. Validator less bootstrap is not supported for other azure tool like azure-powershell, azure-xplat-cli etc.
Note- This changes are in progress!

Added support for validator less bootstrap

---

ChefExtensionHandler/bin/chef-install.sh
ChefExtensionHandler/bin/chef-uninstall.psm1
ChefExtensionHandler/bin/chef-uninstall.sh
ChefExtensionHandler/bin/chef-update.psm1
ChefExtensionHandler/bin/chef-update.sh
ChefExtensionHandler/bin/shared.ps1
ChefExtensionHandler/uninstall.cmd
ChefExtensionHandler/uninstall.sh

Added uninstall_chef_client flag which determines whether to uninstall chef-client or not.

---

ChefExtensionHandler/bin/chef-install.sh

Omnitruck is not supporting chef-client for CentOS version 7. Refer below link
https://docs.chef.io/api_omnitruck.html

Modified sed command to read major version for centos plaform

---

ChefExtensionHandler/bin/chef-install.psm1

For some of the win 2008 OS images, iwr command for file downloading is not recognized, using different approach to fix this issue

Used different way for downloading opscode install.ps1 file for windows

---

lib/chef/azure/commands/enable.rb
spec/unit/azure_enable_spec.rb

When Validation key is base64 encoded using Powershell and during extension running, ruby internally uses the base64 module, due to which the decoded validation key contains all the characters space separated and hence the validation key creation fails
This doesn't happen in case the validation key is encrypted using `base 64` ruby module

Fix for validation.pem file not generating

---

ChefExtensionHandler/bin/chef-install.psm1
lib/chef/azure/service.rb
spec/unit/service_spec.rb

This PR will make the Azure Chef extension install the service by passing a flag to the MSI instead of duplicating the code to create the service.

Added -daemon option in chef-client service install

---

examples/azure-powershell-examples.md
examples/azure-xplat-cli-examples.md
examples/knife-azure-plugin-examples.md

`daemon` option now supports task too.
Update readme details about how users can switch between chef service and scheduled task,
and also explain the usage of `chef-service-interval` option for task and service.

Update Readme to explain usage of daemon option

---

ChefExtensionHandler/bin/shared.ps1
ChefExtensionHandler/enable.cmd
ChefExtensionHandler/install.cmd

1. Move the logic to do .Net settings for Powershell 2 to install phase. Currently it's in enable phase.
2. We are doing File read operation 3 times for getting chef-client version, daemon and environment variables. We should read the file only once and cache it's result.

Optimize extension install and enable for windows.

---

lib/chef/azure/service.rb
spec/unit/service_spec.rb

This PR will make sure that Azure Chef extension start the chef-client service, If service StartMode is disabled.

MSYS-548 - Fixed failing extension for service startmode is disabled.

---

ChefExtensionHandler/bin/chef-update.psm1
ChefExtensionHandler/bin/chef-update.sh
ChefExtensionHandler/bin/shared.ps1

In case of update, the n.settings file doesn't exists initially in the folder of the new extension. This results into following error during extension update:
```
Execution Error:
Get-Content : Could not find a part of the path 'C:\Packages\Plugins\Chef.Boots
trap.WindowsAzure.ChefClient\1210.12.109.9000\RuntimeSettings\'.
At C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.9000\
bin\shared.ps1:211 char:24
+       $json_contents = Get-Content $azure_config_file
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (C:\Packages\Plu...untimeSetting 
s\:String) [Get-Content], DirectoryNotFoundException
+ FullyQualifiedErrorId : GetContentReaderDirectoryNotFoundError,Microsoft 
.PowerShell.Commands.GetContentCommand
```
Hence …

Removing backup logic and using n.settings file from C:\chef during Update

---

Rakefile

Update all existing raketasks related to Public cloud to use `azure-extension-cli` instead of the Rest APIs.
Reasons to do that:
1. `azure-extension-cli` is the recommended way of publishing extension by MSFT.
2. Extensions published by Rest APIs are not available for hours at times.
3. Rest APIs don't list internally published extensions while `azure-extension-cli` does.
4. `azure-extension-cli` is simple and clean.
5. We are already using `azure-extension-cli` to publish extension in GOV cloud. It would be good to have consistency in the approach. We'll be able to use same rake tasks for publishing extension in both clouds.

Use azure-extension-cli to publish/unpublish extension in Public cloud

---

lib/chef/azure/commands/enable.rb

This fixes duplicate node_name in client.rb. This issue found after merging #255 
Signed-off-by: Vasu1105 <vasundhara.jagdale@msystechnologies.com>

Fixes the duplicate node_name in client.rb. 

---

lib/chef/azure/chefhandlers/exception_handler.rb
spec/unit/exception_handler_spec.rb

Currently it is possible for `node` to be `nil`, this causes the `ExceptionHandler` to raise an error instead. This fix ensures that we correctly update the heartbeat on a failure, regardless whether the `node` exists or not.
```
[2018-09-25T13:16:46+00:00] ERROR: Report handler AzureExtension::ExceptionHandler raised #<NoMethodError: undefined method `name' for nil:NilClass>
[2018-09-25T13:16:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/azure-chef-extension-0.0.1/lib/chef/azure/chefhandlers/exception_handler.rb:22:in `report'
[2018-09-25T13:16:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/handler.rb:257:in `run_report_unsafe'
[2018-09-25T13:16:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/handler.rb:24 …
```

Report invalid/missing node correctly in the exception handler

---

ChefExtensionHandler/bin/chef-install.psm1
ChefExtensionHandler/bin/chef-install.sh

Changes will be reverted once chef-15 will be verified stable until then we should hold on the chef's installation till version 14.
Signed-off-by: Nimesh-Msys <nimesh.patni@msystechnologies.com>

Pin to Chef 14 until Chef 15 is tested and verified on Azure later this year

---

lib/chef/azure/templates/chef-client-cron-create.erb

Signed-off-by: dheerajd-msys <dheeraj.dubey@msystechnologies.com>
- Append PATH with `/usr/sbin` to handle execution of general tools like `pam-auth-update`
Fixes https://github.com/chef-partners/azure-chef-extension/issues/268

Set path in cron for chef client environment

---

ChefExtensionHandler/bin/chef-install.psm1

Fix null-valued expression error for powershell command. This code change will now work for both `Chef Client` and `Chef Infra Client` i.e till 14.x and 15.x
```
Execution Error:
Where-Object : You cannot call a method on a null-valued expression.
At C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.13.2.1\bin\chef-install.psm1:30 char:40
+ ... lass Win32_Product | Where-Object { $_.Name.contains("Chef Client") }
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Where-Object], RuntimeException
+ FullyQualifiedErrorId : InvokeMethodOnNull,Microsoft.PowerShell.Commands.WhereObjectCommand
```

Fix null-valued expression error

---

ChefExtensionHandler/bin/chef-install.psm1

Possible fix for #303
I can't test this as I don't have the means to publish Azure Extensions
but with testing at the command line I believe this code may drastically
improve Chef Client download times when using the chef_package_url param.
It basically turns off the progress bar (which shouldn't even be a thing in
headless scripts).
Signed-off-by: Richard Nixon <richard.nixon@btinternet.com>

Possible Fix for 303 Enable times out with chef_package_url param

---

lib/chef/azure/core/bootstrap_context.rb

Probably fixes #298
This fix was not properly tested as I don't have access to publish Azure Extensions.
From manual testing it appears to work with Chef Client 16 on Windows/Linux
Signed-off-by: Richard Nixon <richard.nixon@btinternet.com>

Add support for Chef Client 16

---

ChefExtensionHandler/bin/chef-install.psm1
ChefExtensionHandler/bin/chef-install.sh

Signed-off-by: NAshwini <anehate@chef.io>
Unpin Chef 15 and pin to latest chef version. Done testing with PR https://github.com/chef-partners/azure-chef-extension/pull/308#issuecomment-668576319 so pointing chef to latest version.
Done basic testing on Windows 10, windows 2016, Windows 2019, ubuntu 18, redhat 8 with chef-14, chef-15 and chef-16.
##Issue
#298

Unpin Chef 15 and pin to latest chef version

---

ChefExtensionHandler/bin/parse_env_variables.py
README.md

Signed-off-by: NAshwini <anehate@chef.io>
1. Fix python syntax error found while testing Redhat 8 for environment variable.
2. Updated example of custom_json_attr.
##Issue
https://github.com/chef-partners/azure-chef-extension/issues/319
https://github.com/chef-partners/azure-chef-extension/issues/316

Fix python syntax error found while testing Redhat 8 for environment variable and Updated example of custom_json_attr 

---

README.md

Tags option can be used inside custom_json_attr as `'custom_json_attr': {'tags':['tag1','tag2','tag3']}}'` in azure chef extension.

Updated readme to add tags options example.

---

ChefExtensionHandler/bin/chef-install.psm1

Signed-off-by: Matthew Rogers <matthew.rogers@cloudreach.com>
Address behaviour displayed in issue #331 when recurrent runs of the `chef-client` install occur on a Virtual Machine.
Fixes #331

Remove use of Get Win32_Product API Call

---

ChefExtensionHandler/bin/chef-install.sh

Fixes #338 
Signed-off-by: gscho <greg.c.schofield@gmail.com>

Remove query params from chef_package_url

---

ChefExtensionHandler/bin/shared.ps1

Several customers have recently had issues with Chef client deployments failing during the MSI install phase. In one instance, a large organisation in EMEA is getting about 20% failure on Windows.
This PR adds logging for the MSI installer to help diagnose the failures.
Logs are placed in `c:\WindowsAzure\Logs` with filenames like `ChefMsiInstaller-<timestamp>.log`
**Note:**
This code has not been tested properly as I don't have rights to publish the Azure Chef Extension.
Signed-off-by: Richard Nixon <richard.nixon@btinternet>

Add MSI installer logging

---

ChefExtensionHandler/bin/chef-install.psm1

When customers install Chef using `chef_package_url` from an Azure blob store which has TLSv1.2 enabled (and TLSv1.0 disabled) the install fails on Windows 2016 because its default transport is pinned at TLSv1.0.
This fix should allow it to auto-negotiate by allowing newer versions of TLS (1.1 and 1.2)
NOTE: I have no facility to directly test this fix as I don't have rights to push Azure Extensions.
Signed-off-by: Richard Nixon <richard.nixon@btinternet>

Fix TLS for installs from Azure Blob Stores
